### PR TITLE
Authentication and Private Routes.

### PR DESCRIPTION
**Pull request by samyukthasudhakar**
The PR contains the following authentication features :

- Sign Up
- Log In
- Log Out

Wishlist and Cart pages have set to be restricted routes, meaning without logging in these pages and the respective functionalities cannot be accessed.

Files to be reviewed are part of this [commit](https://github.com/samyukthasudhakar/paws-and-beyond-React/commit/1a8193b5061710737e95deb93e765597c4f18043).

Live Link : https://ecommerce-authentication.netlify.app/

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
good use of `constants` and `alerts`. auth feature is also working fine.

**Review by ApurvaSawant11 — APPROVED** [review]
Everything looks good to me! UI also looks great

Just add some more space on the right side of the login and signup forms. They are on extreme right.

**Comment by samyukthasudhakar** [comment]
> good use of `constants` and `alerts`. auth feature is also working fine.

Thank you !

**Comment by samyukthasudhakar** [comment]
> Everything looks good to me! UI also looks great
> 
> Just add some more space on the right side of the login and signup forms. They are on extreme right.

Thanks Apurva. Will add some more spacing.

**Comment by samyukthasudhakar** [comment]
Thank you @foolhardy21 @ApurvaSawant11 for reviewing the PR. Merging the branch.

**Pull request merged**
